# Generated by Django 5.0.6 on 2024-08-12 05:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('headline', models.TextField()),
                ('sentiment', models.CharField(max_length=10)),
                ('published_at', models.DateTimeField()),
                ('impact_on_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
    ]
